defaults: &defaults
  docker:
    - image: cimg/node:lts-browsers

version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.0

jobs:
  percy:
    <<: *defaults
    resource_class: large
    steps:
      - checkout
      - browser-tools/install-browser-tools
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-node:lts-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run:
          command: yarn percy
          no_output_timeout: 20m
          environment:
            PERCY_BROWSER_EXECUTABLE: /usr/bin/google-chrome
      - save_cache:
          key: yarn-node:lts-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

workflows:
  version: 2
  build_lint_and_test:
    jobs:
      - percy
