defaults: &defaults
  docker:
    - image: cimg/node:22.16-browsers

version: 2.1

orbs:
  browser-tools: circleci/browser-tools@2.4.2

jobs:
  percy:
    <<: *defaults
    resource_class: large
    steps:
      - checkout
      - browser-tools/install-browser-tools:
          install-chrome: false
          install-chrome-for-testing: true
          install-firefox: false
          install-chromedriver: false
          install-geckodriver: false
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-node:22.16-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run:
          command: yarn percy
          environment:
            PERCY_BROWSER_EXECUTABLE: /usr/local/bin/chrome
      - save_cache:
          key: yarn-node:22.16-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

workflows:
  version: 2
  build_lint_and_test:
    jobs:
      - percy
