import classNames from "classnames";
import type { HTMLProps } from "react";
import React from "react";

import type { ClassName, PropsWithSpread, ValueOf } from "types";

export const ICONS = {
  anchor: "anchor",
  chevronDown: "chevron-down",
  chevronLeft: "chevron-left",
  chevronRight: "chevron-right",
  chevronUp: "chevron-up",
  circleOfFriends: "circle-of-friends",
  close: "close",
  code: "code",
  collapse: "collapse",
  copy: "copy",
  delete: "delete",
  drag: "drag",
  error: "error",
  errorGrey: "error-grey",
  expand: "expand",
  externalLink: "external-link",
  help: "help",
  hide: "hide",
  information: "information",
  menu: "menu",
  minus: "minus",
  plus: "plus",
  search: "search",
  share: "share",
  show: "show",
  spinner: "spinner",
  success: "success",
  successGrey: "success-grey",
  user: "user",
  warning: "warning",
  facebook: "facebook",
  twitter: "twitter",
  instagram: "instagram",
  linkedin: "linkedin",
  youtube: "youtube",
  github: "github",
  rss: "rss",
  email: "email",
  // Icons below are not included in Vanilla's `vf-p-icons` mixin, so their
  // styles may need to be included in your project, e.g.
  // `@include vf-p-icon-add-canvas;`.
  addCanvas: "add-canvas",
  addLogicalVolume: "add-logical-volume",
  addPartition: "add-partition",
  applications: "applications",
  archive: "archive",
  arrowBottomLeft: "arrow-bottom-left",
  arrowBottomRight: "arrow-bottom-right",
  arrowDown: "arrow-down",
  arrowLeft: "arrow-left",
  arrowRight: "arrow-right",
  arrowTopLeft: "arrow-top-left",
  arrowTopRight: "arrow-top-right",
  arrowUp: "arrow-up",
  backToTop: "back-to-top",
  beginDownloading: "begin-downloading",
  blueprint: "blueprint",
  book: "book",
  bundle: "bundle",
  canvas: "canvas",
  certificate: "certificate",
  certification: "certification",
  changeVersion: "change-version",
  clusterHost: "cluster-host",
  comments: "comments",
  conflict: "conflict",
  conflictGrey: "conflict-grey",
  conflictResolution: "conflict-resolution",
  conflictResolutionGrey: "conflict-resolution-grey",
  connected: "connected",
  contact: "contact",
  containers: "containers",
  contextualMenu: "contextual-menu",
  controllers: "controllers",
  copyToClipboard: "copy-to-clipboard",
  creditCard: "credit-card",
  cursor: "cursor",
  desktop: "desktop",
  devtools: "devtools",
  devtoolsOff: "devtools-off",
  disconnect: "disconnect",
  edit: "edit",
  export: "export",
  exposed: "exposed",
  file: "file",
  fileBlank: "file-blank",
  filter: "filter",
  folder: "folder",
  fork: "fork",
  fullscreen: "fullscreen",
  generativeAi: "generative-ai",
  getLink: "get-link",
  gift: "gift",
  halfscreenBar: "halfscreen-bar",
  heading: "heading",
  highlightOff: "highlight-off",
  highlightOn: "highlight-on",
  history: "history",
  home: "home",
  ignored: "ignored",
  image: "image",
  import: "import",
  inProgress: "in-progress",
  inspectorDebug: "inspector-debug",
  iso: "iso",
  keyboard: "keyboard",
  keyboardOff: "keyboard-off",
  loadingSteps: "loading-steps",
  location: "location",
  lockLocked: "lock-locked",
  lockLockedActive: "lock-locked-active",
  lockUnlock: "lock-unlock",
  logOut: "log-out",
  machines: "machines",
  map: "map",
  maximiseBar: "maximise-bar",
  minimiseBar: "minimise-bar",
  models: "models",
  mount: "mount",
  mount2: "mount-2",
  notifications: "notifications",
  openTerminal: "open-terminal",
  pause: "pause",
  pin: "pin",
  plans: "plans",
  play: "play",
  pods: "pods",
  powerError: "power-error",
  powerOff: "power-off",
  powerOn: "power-on",
  priorityCritical: "priority-critical",
  priorityHigh: "priority-high",
  priorityLow: "priority-low",
  priorityMedium: "priority-medium",
  priorityNegligible: "priority-negligible",
  priorityUnknown: "priority-unknown",
  privateKey: "private-key",
  profile: "profile",
  profiles: "profiles",
  question: "question",
  quote: "quote",
  repository: "repository",
  resize: "resize",
  resizeOff: "resize-off",
  restart: "restart",
  revisions: "revisions",
  rotateLeft: "rotate-left",
  rotateRight: "rotate-right",
  screenRecordStart: "screen-record-start",
  screenRecordStop: "screen-record-stop",
  screenshot: "screenshot",
  security: "security",
  securityError: "security-error",
  securityTick: "security-tick",
  securityWarning: "security-warning",
  select: "select",
  selectAdd: "select-add",
  selectRemove: "select-remove",
  settings: "settings",
  singleHost: "single-host",
  snapshot: "snapshot",
  snooze: "snooze",
  sortBoth: "sort-both",
  sortDown: "sort-down",
  sortUp: "sort-up",
  starred: "starred",
  statistics: "statistics",
  status: "status",
  statusFailedSmall: "status-failed-small",
  statusInProgress: "status-in-progress",
  statusInProgressSmall: "status-in-progress-small",
  statusQueued: "status-queued",
  statusQueuedSmall: "status-queued-small",
  statusSucceededSmall: "status-succeeded-small",
  statusWaiting: "status-waiting",
  statusWaitingSmall: "status-waiting-small",
  stop: "stop",
  storageBucket: "storage-bucket",
  storagePool: "storage-pool",
  storageVolume: "storage-volume",
  submitBug: "submit-bug",
  switcher: "switcher",
  switcherDashboard: "switcher-dashboard",
  switcherEnvironments: "switcher-environments",
  tag: "tag",
  taskOutstanding: "task-outstanding",
  thumbsDown: "thumbs-down",
  thumbsUp: "thumbs-up",
  tidy: "tidy",
  timedOut: "timed-out",
  timedOutGrey: "timed-out-grey",
  toggleSideNav: "toggle-side-nav",
  topic: "topic",
  turnOffNotification: "turn-off-notification",
  unitPending: "unit-pending",
  unitRunning: "unit-running",
  units: "units",
  unmount: "unmount",
  unstarred: "unstarred",
  upload: "upload",
  usb: "usb",
  userGroup: "user-group",
  videoPlay: "video-play",
  volumeDown: "volume-down",
  volumeUp: "volume-up",
  vulnerable: "vulnerable",
  warningGrey: "warning-grey",
  website: "website",
} as const;

export type Props = PropsWithSpread<
  {
    /**
     * Optional classes to add to the icon element.
     */
    className?: ClassName;
    /**
     * Whether to show the light variant of the icon.
     */
    light?: boolean;
    /**
     * The name of the icon. Icons that are not included in Vanilla's
     * `vf-p-icons` mixin may need their styles to be included in your project,
     * e.g. `@include vf-p-icon-add-canvas;`.
     */
    name: ValueOf<typeof ICONS> | string;
  },
  HTMLProps<HTMLElement>
>;

/**
 * This is a [React](https://reactjs.org/) component for the Vanilla [Icon](https://docs.vanillaframework.io/patterns/icons/).
 *
 * Icons provide visual context and enhance usability.
 *
 * @param name One of built-in Vanilla icons or a name of a custom icon that follows `p-icon--{name}` convention.
 * @returns Icon
 */
const Icon = ({
  className,
  light,
  name,
  ...props
}: Props): React.JSX.Element => (
  <i
    className={classNames(className, `p-icon--${name}`, {
      "is-light": light,
    })}
    {...props}
  />
);

export default Icon;
