name: PR Percy Review Label Required
on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "Review: Percy +1"
          add_comment: true
          message: |
            This PR is being prevented from merging because it needs to be reviewed on Percy.

            Go to [Percy](https://percy.io/bb49709b/react-components), find the build relevant to this PR and check if it looks as expected.

            Once it's approved, add the label `Review: Percy +1` to this PR.
